//INICIO DE SESION
export const INICIO_SESION = 'INICIO_SESION';
export const INICIO_SESION_EXITO = 'INICIO_SESION_EXITO';
export const INICIO_SESION_ERROR = 'INICIO_SESION_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';
export const CERRAR_SESION_EXITO = 'CERRAR_SESION_EXITO';
export const USUARIO_AUTENTICADO = 'USUARIO_AUTENTICADO';
export const ACTIVO_AUTENTICADO = 'ACTIVO_AUTENTICADO';
export const USUARIO_AUTENTICADO_EXITO = 'USUARIO_AUTENTICADO_EXITO';
export const USUARIO_AUTENTICADO_ERROR = 'USUARIO_AUTENTICADO_ERROR';
//USUARIO
export const VER_USUARIOS = 'VER_USUARIOS';
export const VER_USUARIOS_EXITO = 'VER_USUARIOS_EXITO';
export const VER_USUARIOS_ERROR = 'VER_USUARIOS_ERROR';
export const USUARIO_EDITAR = 'USUARIO_EDITAR';
export const GUARDAR_USUARIO_EDITAR = 'GUARDAR_USUARIO_EDITAR';
export const GUARDAR_USUARIO = 'GUARDAR_USUARIO';
export const GUARDAR_USUARIO_EXITO = 'GUARDAR_USUARIO_EXITO';
export const GUARDAR_USUARIO_ERROR = 'GUARDAR_USUARIO_ERROR';
export const EDITAR_USUARIO = 'EDITAR_USUARIO';
export const EDITAR_USUARIO_EXITO = 'EDITAR_USUARIO_EXITO';
export const EDITAR_USUARIO_ERROR = 'EDITAR_USUARIO_ERROR';
