//INICIO DE SESION
export const INICIO_SESION = 'INICIO_SESION';
export const INICIO_SESION_EXITO = 'INICIO_SESION_EXITO';
export const INICIO_SESION_ERROR = 'INICIO_SESION_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';
export const CERRAR_SESION_EXITO = 'CERRAR_SESION_EXITO';
export const USUARIO_AUTENTICADO = 'USUARIO_AUTENTICADO';
export const ACTIVO_AUTENTICADO = 'ACTIVO_AUTENTICADO';
export const USUARIO_AUTENTICADO_EXITO = 'USUARIO_AUTENTICADO_EXITO';
export const USUARIO_AUTENTICADO_ERROR = 'USUARIO_AUTENTICADO_ERROR';
//USUARIO
export const VER_USUARIOS = 'VER_USUARIOS';
export const VER_USUARIOS_EXITO = 'VER_USUARIOS_EXITO';
export const VER_USUARIOS_ERROR = 'VER_USUARIOS_ERROR';
export const USUARIO_EDITAR = 'USUARIO_EDITAR';
export const GUARDAR_USUARIO_EDITAR = 'GUARDAR_USUARIO_EDITAR';
export const GUARDAR_USUARIO = 'GUARDAR_USUARIO';
export const GUARDAR_USUARIO_EXITO = 'GUARDAR_USUARIO_EXITO';
export const GUARDAR_USUARIO_ERROR = 'GUARDAR_USUARIO_ERROR';
export const EDITAR_USUARIO = 'EDITAR_USUARIO';
export const EDITAR_USUARIO_EXITO = 'EDITAR_USUARIO_EXITO';
export const EDITAR_USUARIO_ERROR = 'EDITAR_USUARIO_ERROR';
export const ACTUALIZAR_USUARIO_COLOMBIA = 'ACTUALIZAR_USUARIO_COLOMBIA';
////// editar pago usuario
export const EDITAR_PAGO_USUARIO_EXITO = 'EDITAR_PAGO_USUARIO_EXITO';
export const EDITAR_PAGO_USUARIO_ERROR = 'EDITAR_PAGO_USUARIO_ERROR';

////RESULTADOS PARTIDOS
export const RESULTADO_PARTIDOS = 'RESULTADO_PARTIDOS';
export const RESULTADO_PARTIDOS_EXITO = 'RESULTADO_PARTIDOS_EXITO';
export const RESULTADO_PARTIDOS_ERROR = 'RESULTADO_PARTIDOS_ERROR';
export const RESULTADO_APUESTA = 'RESULTADO_APUESTA';
export const RESULTADO_APUESTA_EXITO = 'RESULTADO_APUESTA_EXITO';
export const LIMPIAR_DETALLE_APUESTA = 'LIMPIAR_DETALLE_APUESTA';

/////RESULTADOS PARTIDOS FIFA - ENVIANDO LOS GOLES
export const ENVIAR_RESULTADOS_FIFA = 'ENVIAR_RESULTADOS_FIFA';
export const ENVIAR_RESULTADOS_FIFA_EXITO = 'ENVIAR_RESULTADOS_FIFA_EXITO';
export const ENVIAR_RESULTADOS_FIFA_ERROR = 'ENVIAR_RESULTADOS_FIFA_ERROR';


/////GUARDAR RESULTADO
export const GUARDAR_RESULTADO_APOSTADOR = 'GUARDAR_RESULTADO_APOSTADOR';

/////OBTENER LOS PARTIDOS
export const OBTENER_PARTIDOS = 'OBTENER_PARTIDOS';
export const OBTENER_PARTIDOS_EXITO = 'OBTENER_PARTIDOS_EXITO';
export const OBTENER_PARTIDOS_ERROR = 'OBTENER_PARTIDOS_ERROR';
////OBTENER LOS RESULTADOS FIFA
export const OBTENER_RESULTADOS_FIFA = 'OBTENER_RESULTADOS_FIFA';
export const OBTENER_RESULTADOS_FIFA_EXITO = 'OBTENER_RESULTADOS_FIFA_EXITO';
export const OBTENER_RESULTADOS_FIFA_ERROR = 'OBTENER_RESULTADOS_FIFA_ERROR';


///////// OBTENER LAS POSICIONES  USUARIO
export const OBTENER_POSICIONES = 'OBTENER_POSICIONES';
export const OBTENER_POSICIONES_EXITO = 'OBTENER_POSICIONES_EXITO';
export const OBTENER_POSICIONES_ERROR = 'OBTENER_POSICIONES_ERROR';

///////// OBTENER DETALLE DE LAS POSICIONES  USUARIO
export const OBTENER_DETALLES_POSICIONES = 'OBTENER_DETALLES_POSICIONES';
export const OBTENER_DETALLES_POSICIONES_EXITO = 'OBTENER_DETALLES_POSICIONES_EXITO';
export const OBTENER_DETALLES_POSICIONES_ERROR = 'OBTENER_DETALLES_POSICIONES_ERROR';


///////// OBTENER LOS RESULTADOS APOSTADOS POR EL USUARIO
export const OBTENER_RESULTADOS = 'OBTENER_RESULTADOS';
export const OBTENER_RESULTADOS_EXITO = 'OBTENER_RESULTADOS_EXITO';
export const OBTENER_RESULTADOS_ERROR = 'OBTENER_RESULTADOS_ERROR';